### ISSUE TITLE
bash syntax error when exporting API on pixel 3. 

### ISSUE THREAD

**Issue by 0-CYBERDYNE-SYSTEMS-0** [Arrendy/open-interpreter-termux#2]
### Description

Experiencing syntax and interpreter issues during the setup of open-interpreter-termux on Pixel 3.

### Environment
- **Device:** Pixel 3
- **OS:** [Android] (Android 12 OS)
- **Software Version:** [Termux] 

### Steps to Reproduce
1. Run the setup for open-interpreter-termux.
2. Execute setup storage without issues.
3. Attempt to export the API key.

### Expected Behavior
[interpreter would open and I would do things.]

### Actual Behavior
Encountered two errors post API key export:

**Errors:** 
```bash
bash: syntax error near unexpected token `newline'



no command interpreter found, did you mean: command interpfilter in package prover9.

**Comment by Arrendy** [comment]
We resolved this by running

`python --version` = 3.11.6
`pip install open-interpreter`
`pip install ruamel.yaml==0.16.12`
