### ISSUE TITLE
open-interpreter==0.1.8 is showing api log

### ISSUE THREAD

**Issue by alexpwrd** [Arrendy/open-interpreter-termux#4]
0.1.8 had the issue of showing the open ai api logs, I tried using open-interpreter 0.1.9 or 0.1.10 but got a dependency error. I downgraded by running pip install open-interpreter==0.1.7 and it worked as expected. 

are we stuck on 0.1.7 version for android termux?

**Comment by Arrendy** [comment]
For the time being, yes. The Open Interpreter team is aware of this and finding a fix is on their to do list. The issue is dependency driven

**Comment by Arrendy** [comment]
Hey @alexpwrd! Just wanted to ping ya that we can now run the latest version of OI

**Comment by alexpwrd** [comment]
thanks!
