### ISSUE TITLE
wget pip install on nix-on-droid nix+termux. 

### ISSUE THREAD

**Issue by ekg** [Arrendy/open-interpreter-termux#5]
Trying to install Open Interpreter in a Termux virtual environment, but it's hitting a snag. There's this permission issue with a temp directory (`/data/data/com.termux.nix/files/usr/tmp/pip-modern-metadata-bjriqhr5/`) – looks like it can't write to it. Seems like the directory might not be there or it's got wrong permissions. Something's off with how the virtual environment or Termux is handling permissions or paths. The pip install fails for wget=3.2 with this error message:

```
Preparing metadata (pyproject.toml) ..[12/564]  error: subprocess-exited-with-error                                                             × Preparing metadata (pyproject.toml) did not run successfully.                                 │ exit code: 1                                  ╰─> [1 lines of output]                             error: [('/data/data/com.termux.nix/files/usr/tmp/pip-modern-metadata-cd83mgpk/wget.egg-info/top_level.txt', '/data/data/com.termux.nix/files/usr/tmp/pip-modern-metadata-cd83mgpk/wget.egg-info.__bkp__/top_level.txt', "[Errno 13] Permission denied: '/data/data/com.termux.nix/files/usr/tmp/pip-modern-metadata-cd83mgpk/wget.egg-info.__bkp__/top_level.txt'"), ('/data/data/com.termux.nix/files/usr/tmp/pip-modern-metadata-cd83mgpk/wget.egg-info/PKG-INFO', '/data/data/com.termux.nix/files/usr/tmp/pip-modern-metadata-cd83mgpk/wget.egg-info.__bkp__/PKG-INFO', "[Errno 13] Permission denied: '/data/data/com.termux.nix/files/usr/tmp/pip-modern-metadata-cd83mgpk/wget.egg-info.__bkp__/PKG-INFO'"), ('/data/data/com.termux.nix/files/usr/tmp/pip-modern-metadata-cd83mgpk/wget.egg-info/dependency_links.txt', '/data/data/com.termux.nix/files/usr/tmp/pip-modern-metadata-cd83mgpk/wget.egg-info.__bkp__/dependency_links.txt', "[Errno 13] Permission denied: '/data/
data/com.termux.nix/files/usr/tmp/pip-modern-met
adata-cd83mgpk/wget.egg-info.__bkp__/dependency_
links.txt'"), ('/data/data/com.termux.nix/files/
usr/tmp/pip-modern-metadata-cd83mgpk/wget.egg-in
fo/SOURCES.txt', '/data/data/com.termux.nix/file
s/usr/tmp/pip-modern-metadata-cd83mgpk/wget.egg-
info.__bkp__/SOURCES.txt', "[Errno 13] Permissio
n denied: '/data/data/com.termux.nix/files/usr/t
mp/pip-modern-metadata-cd83mgpk/wget.egg-info.__
bkp__/SOURCES.txt'"), ('/data/data/com.termux.ni
x/files/usr/tmp/pip-modern-metadata-cd83mgpk/wge
t.egg-info', '/data/data/com.termux.nix/files/us
r/tmp/pip-modern-metadata-cd83mgpk/wget.egg-info
.__bkp__', "[Errno 13] Permission denied: '/data
/data/com.termux.nix/files/usr/tmp/pip-modern-me
tadata-cd83mgpk/wget.egg-info.__bkp__'")]
      [end of output]

  note: This error originates from a subprocess,
 and is likely not a problem with pip.
```

**Comment by Arrendy** [comment]
Have you tried running `termux-setup-storage` twice? 

Running it once prompts the user to allow it to be ran. The second time actually grants storage access

**Comment by ekg** [comment]
On nix-on-droid I don't seem to have the termux-setup-storage command available. Any suggestions to debug or do this another way?

**Comment by Arrendy** [comment]
Unfortunately, I don't at this time. I recently wiped Termux with the goal of starting from scratch. The changes in new OI versions have changed the dependencies and a clean slate would be helpful. I'll be doing it over the holidays, so I'll update you when I get it working

**Comment by ekg** [comment]
I have built from nix-on-droid because it gives a amazingly complete nix distribution. It also helps with setup of llama.cpp. I have been using it to run local models. I wanted to get open-interpreter running on the same system and hook it up to the local model. I got stuck in several ways, including this one. Before getting too much further I should probably check that I can open ports from termux...

**Comment by Arrendy** [comment]
@ekg I just updated the instructions for getting Open Interpreter to work on Termux. Any luck with getting it going on Nix?

**Comment by ekg** [comment]
Unfortunately, no. I decided to write a new bash based CLI frontend
(ekg/yllm) which I plan to add the open-interpreter features to without all
the wild dependencies.

**Comment by Arrendy** [comment]
Starred and will follow your progress! Best of luck!
