### ISSUE TITLE
Error output upgrading new version, after first installing old version. 

### ISSUE THREAD

**Issue by b9Joker108** [Arrendy/open-interpreter-termux#6]
I followed all Termux instructions outlined. Open-interpreter-termux installed. I executed: interpreter. Interpreter advised in shell output that there was a new version and to install it with: pip install --upgrade open-interpreter  which I did, but it outputted quite a long error report which I have pasted to pastebin.com here:

https://pastebin.com/SfHk4bRZ

I could really do with some assistance to resolve this issue.

**Comment by Arrendy** [comment]
Thanks for the detailed information. Unfortunately, I have not figured out how to get the latest updates of Open Interpreter to work on Termux. I do intend on spending some time resolving this but other priorities have to be addressed first. 

My guess is `ninja` is the source of the issue but this needs to be investigated further. If you do attempt any debugging, please share updates here. Thanks

**Comment by Arrendy** [comment]
@b9Joker108 I have updated the instructions and it works on the latest version of Open Interpreter. Please try following the new instructions

**Comment by b9Joker108** [comment]
Thank you so much for spending your valuable time on this and in providing a solution and also, in updating the documentation. I will give it a go and report back.
